DROP DATABASE IF EXISTS tech_database;
CREATE DATABASE tech_database;

\c tech_database;

CREATE TABLE IF NOT EXISTS Owners
(
    OwnerID        INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    OwnerName      VARCHAR(255) NOT NULL,
    OwnerBirthDate DATE         NOT NULL
);

CREATE TABLE IF NOT EXISTS Pets
(
    PetID        INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    PetName      VARCHAR(255) NOT NULL,
    PetBirthDate DATE         NOT NULL,
    OwnerID      INT,
    CONSTRAINT OwnerID FOREIGN KEY (OwnerID) REFERENCES Owners (OwnerID),
    Breed        VARCHAR(255) NOT NULL,
    Color        VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Friends
(
    Pet1ID INTEGER,
    Pet2ID INTEGER,
    CONSTRAINT Pet1ID FOREIGN KEY (Pet1ID) REFERENCES Pets (PetID),
    CONSTRAINT Pet2ID FOREIGN KEY (Pet1ID) REFERENCES Pets (PetID),
    PRIMARY KEY (Pet1ID, Pet2ID)
);