version: '3.9'

services:
  database:
    image: "postgres:15"
    restart: always
    volumes:
      - "./database/init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '1433:5432'
    container_name: "database"


  backend:
    container_name: meow-service
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:80'

  proxy:
    container_name: nginx
    image: nginx:mainline
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'